#change this with your username
username: "RRF_GAMING"

#change to "True" if you want to change proxies
is_proxy_change: False

#change to "True" if you ready to solve captcha
is_show_captcha: True

server:
  StarnixMC:
    -minecraft_mp_com.c
    -minecraft_server_net.c
    -minecraftservers_org.c
    -topg_org.c
    -topminecraftservers_org.c
    -mc_servers_com.c
    -mclist_io
    -mcservertime_com.c